# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  before_all do 
    ensure_git_status_clean(
      show_uncommitted_changes: true,
      show_diff: true
    )
    git_pull
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    get_certificates(
      username: "awhearry@gmail.com"
    )
    get_provisioning_profile(
      username: "awhearry@gmail.com",
      app_identifier: "com.codeinetech.PlasticWeight"
      )
    increment_build_number 
    gym
    upload_to_testflight
  end

  lane :test do
    ensure_git_status_clean(
      show_uncommitted_changes: true,
      show_diff: true
    )
    git_pull
  end

  lane :release do

  end

  desc "capture and deliver screenshots"
  lane :screenshots do
    capture_screenshots
    upload_to_app_store
  end
end
