# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

$username = "awhearry@gmail.com"
$app_identifier = "com.codeinetech.PlasticWeight"


default_platform(:ios)

platform :ios do

  before_all do
    ensure_git_status_clean(
      show_uncommitted_changes: true,
      show_diff: true
    )
    git_pull
    cert(
      username: $username,
      output_path: "./Certificates"
    )
    sigh(
      username: $username,
      app_identifier: $app_identifier,
      output_path: "./Certificates"
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
  	test
    gym(silent: true, export_method: "app-store")
    upload_to_testflight(
      username: $username,
      app_identifier: $app_identifier,
      itc_provider: "HZQ3ZGBLE6",
      beta_app_feedback_email: "allen@codeinecoding.com",
      reject_build_waiting_for_review: true
    )
    increment_build_number(xcodeproj: "PlasticWeight.xcodeproj")
    commit_version_bump(
      message: "Build version bump by fastlane",
      force: true
    )
    add_git_tag(grouping: "Beta")
    push_to_git_remote
    push_git_tags
  end



  lane :release do
  	test
    produce(
      username: $username,
      app_identifier: $app_identifier,
      app_name: "Plastic Weight",
      language: "English",
      app_version: "1.0.2",
    )
    deliver(
      app_version: "1.0.2",
      submit_for_review: true,
      automatic_release: true,
      skip_metadata: true,
    )
    add_git_tag(grouping: "Production")
    push_to_git_remote
    push_git_tags
  end

  desc "capture and deliver screenshots"
  lane :screenshots do
    snapshot(
      app_identifier: $app_identifier,
      clear_previous_screenshots: true
    )
  end

  desc "Run Unit & UITests"
  private_lane :test do
    run_tests(scheme: "PlasticWeightTests")
  end

  after_all do
    push_to_git_remote
  end
end
