# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

$username = "awhearry@gmail.com"
$app_identifier = "com.codeinetech.PlasticWeight"


default_platform(:ios)

platform :ios do

  before_all do 
    ensure_git_status_clean(
      show_uncommitted_changes: true,
      show_diff: true
    )
    git_pull
    cert(
      username: $username,
      output_path: "./Certificates"
    )
    sigh(
      username: $username,
      app_identifier: $app_identifier,
      output_path: "./Certificates"
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number 
    gym
    upload_to_testflight(
      username: $username,
      app_identifier: $app_identifier,
      itc_provider: "HZQ3ZGBLE6",
      beta_app_feedback_email: "allen@codeinecoding.com",
      reject_build_waiting_for_review: true
    )
  end

  lane :test do
    ensure_git_status_clean(
      show_uncommitted_changes: true,
      show_diff: true
    )
    git_pull
  end

  lane :release do
    produce(
      username: $username,
      app_identifier: $app_identifier,
      app_name: "Plastic Weight",
      language: "English",
      app_version: "1.0",
    )
    deliver(
      build_number: "8",
      submit_for_review: true,
      automatic_release: true,
    )

  end

  desc "capture and deliver screenshots"
  lane :screenshots do
    snapshot(
      app_identifier: $app_identifier,
      clear_previous_screenshots: true
    )
  end

  after_all do
    push_to_git_remote
  end
end
